/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as borrowProtocolSol from "./BorrowProtocol.sol";
export type { borrowProtocolSol };
export type { YieldPool } from "./YieldPool";
export type { YieldToken } from "./YieldToken";
