/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IYieldPool,
  IYieldPoolInterface,
} from "../../../contracts/BorrowProtocol.sol/IYieldPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "isTokenAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IYieldPool__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldPoolInterface {
    return new Interface(_abi) as IYieldPoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IYieldPool {
    return new Contract(address, _abi, runner) as unknown as IYieldPool;
  }
}
